### ISSUE TITLE
Is `#` supposed to be inserted at the search string?

### ISSUE THREAD

**Issue by JordanAnthonyKing** [jthaman/consult-everything#5]
You can see this in the readme: 
![image](https://user-images.githubusercontent.com/58787893/203564786-3de03fbc-da37-4c86-b03d-72d825e9ab44.png)

Is this a prefix key? As far as I can tell it doesn't seem to do anything. Looking at the code I can't see where this is inserted.

**Comment by AnabasisXu** [comment]
`#` allows you to do a lot of search tricks. Check out [How to filter search results with Vertico - User Support - Doom Emacs Discourse](https://discourse.doomemacs.org/t/how-to-filter-search-results-with-vertico/2518/2)
